name: better_life_customer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  api:
    path: packages/api
  api_client:
    path: packages/api_client
  bloc: ^8.1.1
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2

  # flutter_localizations:
  #   sdk: flutter

  flutter_native_splash: ^2.2.19
  flutter_screenutil: ^5.9.0
  hive_storage:
    path: packages/hive_storage
  notifications:
    path: packages/notifications
  # intl: ^0.17.0
  lottie: ^2.2.0

  my_theme:
    path: packages/my_theme
  intents:
    path: packages/intents
  path_provider: ^2.0.13
  pin_code_text_field: ^1.8.0
  qr_flutter: ^4.0.0
  text_fields:
    path: packages/text_fields
  widgets:
    path: packages/widgets
  date_format:
    path: packages/date_format
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.0.3+4
  flutter_svg: ^2.0.5
  photo_view: ^0.14.0
  url_launcher: ^6.1.10
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  permission_handler: ^11.3.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/
    - assets/animations/

  uses-material-design: true
  generate: true

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#ffffff'
  image: 'assets/logo.png'
  android: true
  ios: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: false
  ios: true
  image_path: 'assets/logo.png'
  adaptive_icon_background: '#ffffff'

dependency_overrides:
  intl: ^0.17.0
